//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.0
//     from Assets/Samples/XR Interaction Toolkit/2.6.5/XR Device Simulator/XR Device Simulator Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Samples/XR Interaction Toolkit/2.6.5/XR Device Simulator/XR Device Simulator Controls.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @XRDeviceSimulatorControls: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @XRDeviceSimulatorControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""XR Device Simulator Controls"",
    ""maps"": [
        {
            ""name"": ""Main"",
            ""id"": ""c96c4ddb-3eb8-4074-bbd9-a8ae6f1f6475"",
            ""actions"": [
                {
                    ""name"": ""Keyboard X Translate"",
                    ""type"": ""Value"",
                    ""id"": ""d4eb7006-5077-4816-9d5c-f570b6d586f3"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Keyboard Z Translate"",
                    ""type"": ""Value"",
                    ""id"": ""3ea275ac-e111-4610-891f-105676c72cd5"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Keyboard Y Translate"",
                    ""type"": ""Value"",
                    ""id"": ""5cc58f95-e9dc-4675-a42e-dd66874c3ba3"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Toggle Manipulate Left"",
                    ""type"": ""Button"",
                    ""id"": ""847b79d9-a69b-4484-8688-a4bf40e58163"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Toggle Manipulate Right"",
                    ""type"": ""Button"",
                    ""id"": ""241f6068-ebc8-4c6d-b747-8bc2c1f74f87"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Toggle Manipulate Body"",
                    ""type"": ""Button"",
                    ""id"": ""c81093ea-c17e-4430-a3df-bccabef74af4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Manipulate Left"",
                    ""type"": ""Button"",
                    ""id"": ""07c46cc4-c35d-4364-a878-68fad8ab8c64"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Manipulate Right"",
                    ""type"": ""Button"",
                    ""id"": ""307cb608-f32e-48a3-8ce6-d1cd83a5fb90"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Manipulate Head"",
                    ""type"": ""Button"",
                    ""id"": ""f5febf74-651b-4f73-8d0a-08b0acdabc4d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hand-Controller Mode"",
                    ""type"": ""Button"",
                    ""id"": ""31a82fde-55bc-4b18-b15a-8adc7e75658e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cycle Devices"",
                    ""type"": ""Button"",
                    ""id"": ""d728c6fb-4deb-4268-9110-d64c7861cd17"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Stop Manipulation"",
                    ""type"": ""Button"",
                    ""id"": ""974ae49e-da4e-4dc8-a6be-cb63986d8f8e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Mouse Delta"",
                    ""type"": ""Value"",
                    ""id"": ""0b945dbf-d750-40cb-97c6-593686fcf012"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Mouse Scroll"",
                    ""type"": ""Value"",
                    ""id"": ""b2a408da-a9fd-4638-9af3-17fb9bc2811d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rotate Mode Override"",
                    ""type"": ""Button"",
                    ""id"": ""2e390909-c0f6-4ca5-b8bc-4c54090f96d9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Toggle Mouse Transformation Mode"",
                    ""type"": ""Button"",
                    ""id"": ""ae2b5c7f-b5e0-4b93-b674-172de9f68380"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Negate Mode"",
                    ""type"": ""Button"",
                    ""id"": ""8c837143-e018-41f0-9e0e-907acb9d7360"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Z Constraint"",
                    ""type"": ""Button"",
                    ""id"": ""d3e9308c-6f8c-46f7-bb6f-14422c345983"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""X Constraint"",
                    ""type"": ""Button"",
                    ""id"": ""11dc7a94-7230-49ff-b56d-06e6473e9951"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Y Constraint"",
                    ""type"": ""Button"",
                    ""id"": ""11ab79c6-b9c6-4301-8086-3e9c6904ef14"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reset"",
                    ""type"": ""Button"",
                    ""id"": ""339ccb79-aee9-4ba4-8864-3b6c81c199db"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Toggle Cursor Lock"",
                    ""type"": ""Button"",
                    ""id"": ""9bd36ab1-f676-4ff4-8a4d-ba0c6fb36268"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Toggle Primary 2D Axis Target"",
                    ""type"": ""Button"",
                    ""id"": ""e0fdec2d-309b-4313-aad7-9dcc71f1394d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Toggle Secondary 2D Axis Target"",
                    ""type"": ""Button"",
                    ""id"": ""b3b49ea5-f80f-4d24-a782-d61a13a004b3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Toggle Device Position Target"",
                    ""type"": ""Button"",
                    ""id"": ""15cd3c4a-56b1-4a43-a924-a2118e2adaf4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""db741065-2a46-439d-9e13-11960dc3355a"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Keyboard X Translate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""3d2e07de-025e-4c2e-98df-250511a8ff6d"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Keyboard X Translate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""04e1437d-c862-4a04-8f8e-40e9f52c4f5e"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Keyboard X Translate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""cb7c4679-31f4-4170-885a-e7d78c049443"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Keyboard Z Translate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""732e790c-f2a2-4f90-b525-53139a358de7"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Keyboard Z Translate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""d5a98916-ade7-419d-a138-86bcdf05670f"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Keyboard Z Translate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""fca20498-bf6f-4824-ba15-6dc2d191eb2f"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Keyboard Y Translate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""2c01790c-a24a-4266-a2e9-74e2a1ca3fa7"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Keyboard Y Translate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""f5223aed-93c0-4633-8aa3-c393ce890872"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Keyboard Y Translate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""fcfb16fb-edee-474c-b1f2-f10b2a0a3569"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Manipulate Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e791caef-78d3-4f68-9104-212f73ac0642"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Manipulate Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b2c1b1cd-6ea7-45b6-b68f-17b3662b4d3a"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mouse Delta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""66e536bc-b5b6-4c7b-903a-fbcc05fc854e"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mouse Scroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2b070a4a-e044-4cbd-a8e2-6b362785bf21"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate Mode Override"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0fa0d566-1e07-4e17-9b14-3e8fce69ec26"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""X Constraint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""71c185e1-73fb-4691-b910-70610f397b42"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Y Constraint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""09809c10-d09e-4c49-b58f-1995e50cf685"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Z Constraint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7611d6eb-0ff4-431f-998d-6fa429e0e1e1"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle Mouse Transformation Mode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5c889b78-f9fd-4cd7-96dd-5399428f6992"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Negate Mode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""85f27bdb-dfe8-48d3-8512-205b3ad6306a"",
                    ""path"": ""<Keyboard>/backslash"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle Cursor Lock"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3542472e-e883-407a-b967-5b879b2d7dc4"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Manipulate Head"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cd7dcdd6-b569-4c25-87ea-c62a0fb1cf89"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reset"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4bfdd0e6-1936-4f44-8e97-20e16dbc879f"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle Primary 2D Axis Target"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""81d47d9e-4920-4098-94d8-bac2888d6433"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle Secondary 2D Axis Target"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9404bec7-672a-4fb1-adb3-e2dc4e32801b"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle Device Position Target"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5dacc4c7-2e70-4500-8c72-99595c72b49e"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cycle Devices"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""84760c74-7de6-46dd-a097-3bc198cf63cd"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stop Manipulation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e8a0a3b9-06cf-40a8-86d8-1d8f1d704451"",
                    ""path"": ""<Keyboard>/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle Manipulate Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b62df009-54c9-4b03-9721-07ca66fe1bdf"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle Manipulate Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""51f71c9d-9024-4bdd-8ea6-19b987e261b1"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle Manipulate Body"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d7d20173-13ae-4c9f-b6a9-bf8a89517d6a"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hand-Controller Mode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Main
        m_Main = asset.FindActionMap("Main", throwIfNotFound: true);
        m_Main_KeyboardXTranslate = m_Main.FindAction("Keyboard X Translate", throwIfNotFound: true);
        m_Main_KeyboardZTranslate = m_Main.FindAction("Keyboard Z Translate", throwIfNotFound: true);
        m_Main_KeyboardYTranslate = m_Main.FindAction("Keyboard Y Translate", throwIfNotFound: true);
        m_Main_ToggleManipulateLeft = m_Main.FindAction("Toggle Manipulate Left", throwIfNotFound: true);
        m_Main_ToggleManipulateRight = m_Main.FindAction("Toggle Manipulate Right", throwIfNotFound: true);
        m_Main_ToggleManipulateBody = m_Main.FindAction("Toggle Manipulate Body", throwIfNotFound: true);
        m_Main_ManipulateLeft = m_Main.FindAction("Manipulate Left", throwIfNotFound: true);
        m_Main_ManipulateRight = m_Main.FindAction("Manipulate Right", throwIfNotFound: true);
        m_Main_ManipulateHead = m_Main.FindAction("Manipulate Head", throwIfNotFound: true);
        m_Main_HandControllerMode = m_Main.FindAction("Hand-Controller Mode", throwIfNotFound: true);
        m_Main_CycleDevices = m_Main.FindAction("Cycle Devices", throwIfNotFound: true);
        m_Main_StopManipulation = m_Main.FindAction("Stop Manipulation", throwIfNotFound: true);
        m_Main_MouseDelta = m_Main.FindAction("Mouse Delta", throwIfNotFound: true);
        m_Main_MouseScroll = m_Main.FindAction("Mouse Scroll", throwIfNotFound: true);
        m_Main_RotateModeOverride = m_Main.FindAction("Rotate Mode Override", throwIfNotFound: true);
        m_Main_ToggleMouseTransformationMode = m_Main.FindAction("Toggle Mouse Transformation Mode", throwIfNotFound: true);
        m_Main_NegateMode = m_Main.FindAction("Negate Mode", throwIfNotFound: true);
        m_Main_ZConstraint = m_Main.FindAction("Z Constraint", throwIfNotFound: true);
        m_Main_XConstraint = m_Main.FindAction("X Constraint", throwIfNotFound: true);
        m_Main_YConstraint = m_Main.FindAction("Y Constraint", throwIfNotFound: true);
        m_Main_Reset = m_Main.FindAction("Reset", throwIfNotFound: true);
        m_Main_ToggleCursorLock = m_Main.FindAction("Toggle Cursor Lock", throwIfNotFound: true);
        m_Main_TogglePrimary2DAxisTarget = m_Main.FindAction("Toggle Primary 2D Axis Target", throwIfNotFound: true);
        m_Main_ToggleSecondary2DAxisTarget = m_Main.FindAction("Toggle Secondary 2D Axis Target", throwIfNotFound: true);
        m_Main_ToggleDevicePositionTarget = m_Main.FindAction("Toggle Device Position Target", throwIfNotFound: true);
    }

    ~@XRDeviceSimulatorControls()
    {
        UnityEngine.Debug.Assert(!m_Main.enabled, "This will cause a leak and performance issues, XRDeviceSimulatorControls.Main.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Main
    private readonly InputActionMap m_Main;
    private List<IMainActions> m_MainActionsCallbackInterfaces = new List<IMainActions>();
    private readonly InputAction m_Main_KeyboardXTranslate;
    private readonly InputAction m_Main_KeyboardZTranslate;
    private readonly InputAction m_Main_KeyboardYTranslate;
    private readonly InputAction m_Main_ToggleManipulateLeft;
    private readonly InputAction m_Main_ToggleManipulateRight;
    private readonly InputAction m_Main_ToggleManipulateBody;
    private readonly InputAction m_Main_ManipulateLeft;
    private readonly InputAction m_Main_ManipulateRight;
    private readonly InputAction m_Main_ManipulateHead;
    private readonly InputAction m_Main_HandControllerMode;
    private readonly InputAction m_Main_CycleDevices;
    private readonly InputAction m_Main_StopManipulation;
    private readonly InputAction m_Main_MouseDelta;
    private readonly InputAction m_Main_MouseScroll;
    private readonly InputAction m_Main_RotateModeOverride;
    private readonly InputAction m_Main_ToggleMouseTransformationMode;
    private readonly InputAction m_Main_NegateMode;
    private readonly InputAction m_Main_ZConstraint;
    private readonly InputAction m_Main_XConstraint;
    private readonly InputAction m_Main_YConstraint;
    private readonly InputAction m_Main_Reset;
    private readonly InputAction m_Main_ToggleCursorLock;
    private readonly InputAction m_Main_TogglePrimary2DAxisTarget;
    private readonly InputAction m_Main_ToggleSecondary2DAxisTarget;
    private readonly InputAction m_Main_ToggleDevicePositionTarget;
    /// <summary>
    /// Provides access to input actions defined in input action map "Main".
    /// </summary>
    public struct MainActions
    {
        private @XRDeviceSimulatorControls m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public MainActions(@XRDeviceSimulatorControls wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Main/KeyboardXTranslate".
        /// </summary>
        public InputAction @KeyboardXTranslate => m_Wrapper.m_Main_KeyboardXTranslate;
        /// <summary>
        /// Provides access to the underlying input action "Main/KeyboardZTranslate".
        /// </summary>
        public InputAction @KeyboardZTranslate => m_Wrapper.m_Main_KeyboardZTranslate;
        /// <summary>
        /// Provides access to the underlying input action "Main/KeyboardYTranslate".
        /// </summary>
        public InputAction @KeyboardYTranslate => m_Wrapper.m_Main_KeyboardYTranslate;
        /// <summary>
        /// Provides access to the underlying input action "Main/ToggleManipulateLeft".
        /// </summary>
        public InputAction @ToggleManipulateLeft => m_Wrapper.m_Main_ToggleManipulateLeft;
        /// <summary>
        /// Provides access to the underlying input action "Main/ToggleManipulateRight".
        /// </summary>
        public InputAction @ToggleManipulateRight => m_Wrapper.m_Main_ToggleManipulateRight;
        /// <summary>
        /// Provides access to the underlying input action "Main/ToggleManipulateBody".
        /// </summary>
        public InputAction @ToggleManipulateBody => m_Wrapper.m_Main_ToggleManipulateBody;
        /// <summary>
        /// Provides access to the underlying input action "Main/ManipulateLeft".
        /// </summary>
        public InputAction @ManipulateLeft => m_Wrapper.m_Main_ManipulateLeft;
        /// <summary>
        /// Provides access to the underlying input action "Main/ManipulateRight".
        /// </summary>
        public InputAction @ManipulateRight => m_Wrapper.m_Main_ManipulateRight;
        /// <summary>
        /// Provides access to the underlying input action "Main/ManipulateHead".
        /// </summary>
        public InputAction @ManipulateHead => m_Wrapper.m_Main_ManipulateHead;
        /// <summary>
        /// Provides access to the underlying input action "Main/HandControllerMode".
        /// </summary>
        public InputAction @HandControllerMode => m_Wrapper.m_Main_HandControllerMode;
        /// <summary>
        /// Provides access to the underlying input action "Main/CycleDevices".
        /// </summary>
        public InputAction @CycleDevices => m_Wrapper.m_Main_CycleDevices;
        /// <summary>
        /// Provides access to the underlying input action "Main/StopManipulation".
        /// </summary>
        public InputAction @StopManipulation => m_Wrapper.m_Main_StopManipulation;
        /// <summary>
        /// Provides access to the underlying input action "Main/MouseDelta".
        /// </summary>
        public InputAction @MouseDelta => m_Wrapper.m_Main_MouseDelta;
        /// <summary>
        /// Provides access to the underlying input action "Main/MouseScroll".
        /// </summary>
        public InputAction @MouseScroll => m_Wrapper.m_Main_MouseScroll;
        /// <summary>
        /// Provides access to the underlying input action "Main/RotateModeOverride".
        /// </summary>
        public InputAction @RotateModeOverride => m_Wrapper.m_Main_RotateModeOverride;
        /// <summary>
        /// Provides access to the underlying input action "Main/ToggleMouseTransformationMode".
        /// </summary>
        public InputAction @ToggleMouseTransformationMode => m_Wrapper.m_Main_ToggleMouseTransformationMode;
        /// <summary>
        /// Provides access to the underlying input action "Main/NegateMode".
        /// </summary>
        public InputAction @NegateMode => m_Wrapper.m_Main_NegateMode;
        /// <summary>
        /// Provides access to the underlying input action "Main/ZConstraint".
        /// </summary>
        public InputAction @ZConstraint => m_Wrapper.m_Main_ZConstraint;
        /// <summary>
        /// Provides access to the underlying input action "Main/XConstraint".
        /// </summary>
        public InputAction @XConstraint => m_Wrapper.m_Main_XConstraint;
        /// <summary>
        /// Provides access to the underlying input action "Main/YConstraint".
        /// </summary>
        public InputAction @YConstraint => m_Wrapper.m_Main_YConstraint;
        /// <summary>
        /// Provides access to the underlying input action "Main/Reset".
        /// </summary>
        public InputAction @Reset => m_Wrapper.m_Main_Reset;
        /// <summary>
        /// Provides access to the underlying input action "Main/ToggleCursorLock".
        /// </summary>
        public InputAction @ToggleCursorLock => m_Wrapper.m_Main_ToggleCursorLock;
        /// <summary>
        /// Provides access to the underlying input action "Main/TogglePrimary2DAxisTarget".
        /// </summary>
        public InputAction @TogglePrimary2DAxisTarget => m_Wrapper.m_Main_TogglePrimary2DAxisTarget;
        /// <summary>
        /// Provides access to the underlying input action "Main/ToggleSecondary2DAxisTarget".
        /// </summary>
        public InputAction @ToggleSecondary2DAxisTarget => m_Wrapper.m_Main_ToggleSecondary2DAxisTarget;
        /// <summary>
        /// Provides access to the underlying input action "Main/ToggleDevicePositionTarget".
        /// </summary>
        public InputAction @ToggleDevicePositionTarget => m_Wrapper.m_Main_ToggleDevicePositionTarget;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Main; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="MainActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(MainActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="MainActions" />
        public void AddCallbacks(IMainActions instance)
        {
            if (instance == null || m_Wrapper.m_MainActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MainActionsCallbackInterfaces.Add(instance);
            @KeyboardXTranslate.started += instance.OnKeyboardXTranslate;
            @KeyboardXTranslate.performed += instance.OnKeyboardXTranslate;
            @KeyboardXTranslate.canceled += instance.OnKeyboardXTranslate;
            @KeyboardZTranslate.started += instance.OnKeyboardZTranslate;
            @KeyboardZTranslate.performed += instance.OnKeyboardZTranslate;
            @KeyboardZTranslate.canceled += instance.OnKeyboardZTranslate;
            @KeyboardYTranslate.started += instance.OnKeyboardYTranslate;
            @KeyboardYTranslate.performed += instance.OnKeyboardYTranslate;
            @KeyboardYTranslate.canceled += instance.OnKeyboardYTranslate;
            @ToggleManipulateLeft.started += instance.OnToggleManipulateLeft;
            @ToggleManipulateLeft.performed += instance.OnToggleManipulateLeft;
            @ToggleManipulateLeft.canceled += instance.OnToggleManipulateLeft;
            @ToggleManipulateRight.started += instance.OnToggleManipulateRight;
            @ToggleManipulateRight.performed += instance.OnToggleManipulateRight;
            @ToggleManipulateRight.canceled += instance.OnToggleManipulateRight;
            @ToggleManipulateBody.started += instance.OnToggleManipulateBody;
            @ToggleManipulateBody.performed += instance.OnToggleManipulateBody;
            @ToggleManipulateBody.canceled += instance.OnToggleManipulateBody;
            @ManipulateLeft.started += instance.OnManipulateLeft;
            @ManipulateLeft.performed += instance.OnManipulateLeft;
            @ManipulateLeft.canceled += instance.OnManipulateLeft;
            @ManipulateRight.started += instance.OnManipulateRight;
            @ManipulateRight.performed += instance.OnManipulateRight;
            @ManipulateRight.canceled += instance.OnManipulateRight;
            @ManipulateHead.started += instance.OnManipulateHead;
            @ManipulateHead.performed += instance.OnManipulateHead;
            @ManipulateHead.canceled += instance.OnManipulateHead;
            @HandControllerMode.started += instance.OnHandControllerMode;
            @HandControllerMode.performed += instance.OnHandControllerMode;
            @HandControllerMode.canceled += instance.OnHandControllerMode;
            @CycleDevices.started += instance.OnCycleDevices;
            @CycleDevices.performed += instance.OnCycleDevices;
            @CycleDevices.canceled += instance.OnCycleDevices;
            @StopManipulation.started += instance.OnStopManipulation;
            @StopManipulation.performed += instance.OnStopManipulation;
            @StopManipulation.canceled += instance.OnStopManipulation;
            @MouseDelta.started += instance.OnMouseDelta;
            @MouseDelta.performed += instance.OnMouseDelta;
            @MouseDelta.canceled += instance.OnMouseDelta;
            @MouseScroll.started += instance.OnMouseScroll;
            @MouseScroll.performed += instance.OnMouseScroll;
            @MouseScroll.canceled += instance.OnMouseScroll;
            @RotateModeOverride.started += instance.OnRotateModeOverride;
            @RotateModeOverride.performed += instance.OnRotateModeOverride;
            @RotateModeOverride.canceled += instance.OnRotateModeOverride;
            @ToggleMouseTransformationMode.started += instance.OnToggleMouseTransformationMode;
            @ToggleMouseTransformationMode.performed += instance.OnToggleMouseTransformationMode;
            @ToggleMouseTransformationMode.canceled += instance.OnToggleMouseTransformationMode;
            @NegateMode.started += instance.OnNegateMode;
            @NegateMode.performed += instance.OnNegateMode;
            @NegateMode.canceled += instance.OnNegateMode;
            @ZConstraint.started += instance.OnZConstraint;
            @ZConstraint.performed += instance.OnZConstraint;
            @ZConstraint.canceled += instance.OnZConstraint;
            @XConstraint.started += instance.OnXConstraint;
            @XConstraint.performed += instance.OnXConstraint;
            @XConstraint.canceled += instance.OnXConstraint;
            @YConstraint.started += instance.OnYConstraint;
            @YConstraint.performed += instance.OnYConstraint;
            @YConstraint.canceled += instance.OnYConstraint;
            @Reset.started += instance.OnReset;
            @Reset.performed += instance.OnReset;
            @Reset.canceled += instance.OnReset;
            @ToggleCursorLock.started += instance.OnToggleCursorLock;
            @ToggleCursorLock.performed += instance.OnToggleCursorLock;
            @ToggleCursorLock.canceled += instance.OnToggleCursorLock;
            @TogglePrimary2DAxisTarget.started += instance.OnTogglePrimary2DAxisTarget;
            @TogglePrimary2DAxisTarget.performed += instance.OnTogglePrimary2DAxisTarget;
            @TogglePrimary2DAxisTarget.canceled += instance.OnTogglePrimary2DAxisTarget;
            @ToggleSecondary2DAxisTarget.started += instance.OnToggleSecondary2DAxisTarget;
            @ToggleSecondary2DAxisTarget.performed += instance.OnToggleSecondary2DAxisTarget;
            @ToggleSecondary2DAxisTarget.canceled += instance.OnToggleSecondary2DAxisTarget;
            @ToggleDevicePositionTarget.started += instance.OnToggleDevicePositionTarget;
            @ToggleDevicePositionTarget.performed += instance.OnToggleDevicePositionTarget;
            @ToggleDevicePositionTarget.canceled += instance.OnToggleDevicePositionTarget;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="MainActions" />
        private void UnregisterCallbacks(IMainActions instance)
        {
            @KeyboardXTranslate.started -= instance.OnKeyboardXTranslate;
            @KeyboardXTranslate.performed -= instance.OnKeyboardXTranslate;
            @KeyboardXTranslate.canceled -= instance.OnKeyboardXTranslate;
            @KeyboardZTranslate.started -= instance.OnKeyboardZTranslate;
            @KeyboardZTranslate.performed -= instance.OnKeyboardZTranslate;
            @KeyboardZTranslate.canceled -= instance.OnKeyboardZTranslate;
            @KeyboardYTranslate.started -= instance.OnKeyboardYTranslate;
            @KeyboardYTranslate.performed -= instance.OnKeyboardYTranslate;
            @KeyboardYTranslate.canceled -= instance.OnKeyboardYTranslate;
            @ToggleManipulateLeft.started -= instance.OnToggleManipulateLeft;
            @ToggleManipulateLeft.performed -= instance.OnToggleManipulateLeft;
            @ToggleManipulateLeft.canceled -= instance.OnToggleManipulateLeft;
            @ToggleManipulateRight.started -= instance.OnToggleManipulateRight;
            @ToggleManipulateRight.performed -= instance.OnToggleManipulateRight;
            @ToggleManipulateRight.canceled -= instance.OnToggleManipulateRight;
            @ToggleManipulateBody.started -= instance.OnToggleManipulateBody;
            @ToggleManipulateBody.performed -= instance.OnToggleManipulateBody;
            @ToggleManipulateBody.canceled -= instance.OnToggleManipulateBody;
            @ManipulateLeft.started -= instance.OnManipulateLeft;
            @ManipulateLeft.performed -= instance.OnManipulateLeft;
            @ManipulateLeft.canceled -= instance.OnManipulateLeft;
            @ManipulateRight.started -= instance.OnManipulateRight;
            @ManipulateRight.performed -= instance.OnManipulateRight;
            @ManipulateRight.canceled -= instance.OnManipulateRight;
            @ManipulateHead.started -= instance.OnManipulateHead;
            @ManipulateHead.performed -= instance.OnManipulateHead;
            @ManipulateHead.canceled -= instance.OnManipulateHead;
            @HandControllerMode.started -= instance.OnHandControllerMode;
            @HandControllerMode.performed -= instance.OnHandControllerMode;
            @HandControllerMode.canceled -= instance.OnHandControllerMode;
            @CycleDevices.started -= instance.OnCycleDevices;
            @CycleDevices.performed -= instance.OnCycleDevices;
            @CycleDevices.canceled -= instance.OnCycleDevices;
            @StopManipulation.started -= instance.OnStopManipulation;
            @StopManipulation.performed -= instance.OnStopManipulation;
            @StopManipulation.canceled -= instance.OnStopManipulation;
            @MouseDelta.started -= instance.OnMouseDelta;
            @MouseDelta.performed -= instance.OnMouseDelta;
            @MouseDelta.canceled -= instance.OnMouseDelta;
            @MouseScroll.started -= instance.OnMouseScroll;
            @MouseScroll.performed -= instance.OnMouseScroll;
            @MouseScroll.canceled -= instance.OnMouseScroll;
            @RotateModeOverride.started -= instance.OnRotateModeOverride;
            @RotateModeOverride.performed -= instance.OnRotateModeOverride;
            @RotateModeOverride.canceled -= instance.OnRotateModeOverride;
            @ToggleMouseTransformationMode.started -= instance.OnToggleMouseTransformationMode;
            @ToggleMouseTransformationMode.performed -= instance.OnToggleMouseTransformationMode;
            @ToggleMouseTransformationMode.canceled -= instance.OnToggleMouseTransformationMode;
            @NegateMode.started -= instance.OnNegateMode;
            @NegateMode.performed -= instance.OnNegateMode;
            @NegateMode.canceled -= instance.OnNegateMode;
            @ZConstraint.started -= instance.OnZConstraint;
            @ZConstraint.performed -= instance.OnZConstraint;
            @ZConstraint.canceled -= instance.OnZConstraint;
            @XConstraint.started -= instance.OnXConstraint;
            @XConstraint.performed -= instance.OnXConstraint;
            @XConstraint.canceled -= instance.OnXConstraint;
            @YConstraint.started -= instance.OnYConstraint;
            @YConstraint.performed -= instance.OnYConstraint;
            @YConstraint.canceled -= instance.OnYConstraint;
            @Reset.started -= instance.OnReset;
            @Reset.performed -= instance.OnReset;
            @Reset.canceled -= instance.OnReset;
            @ToggleCursorLock.started -= instance.OnToggleCursorLock;
            @ToggleCursorLock.performed -= instance.OnToggleCursorLock;
            @ToggleCursorLock.canceled -= instance.OnToggleCursorLock;
            @TogglePrimary2DAxisTarget.started -= instance.OnTogglePrimary2DAxisTarget;
            @TogglePrimary2DAxisTarget.performed -= instance.OnTogglePrimary2DAxisTarget;
            @TogglePrimary2DAxisTarget.canceled -= instance.OnTogglePrimary2DAxisTarget;
            @ToggleSecondary2DAxisTarget.started -= instance.OnToggleSecondary2DAxisTarget;
            @ToggleSecondary2DAxisTarget.performed -= instance.OnToggleSecondary2DAxisTarget;
            @ToggleSecondary2DAxisTarget.canceled -= instance.OnToggleSecondary2DAxisTarget;
            @ToggleDevicePositionTarget.started -= instance.OnToggleDevicePositionTarget;
            @ToggleDevicePositionTarget.performed -= instance.OnToggleDevicePositionTarget;
            @ToggleDevicePositionTarget.canceled -= instance.OnToggleDevicePositionTarget;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="MainActions.UnregisterCallbacks(IMainActions)" />.
        /// </summary>
        /// <seealso cref="MainActions.UnregisterCallbacks(IMainActions)" />
        public void RemoveCallbacks(IMainActions instance)
        {
            if (m_Wrapper.m_MainActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="MainActions.AddCallbacks(IMainActions)" />
        /// <seealso cref="MainActions.RemoveCallbacks(IMainActions)" />
        /// <seealso cref="MainActions.UnregisterCallbacks(IMainActions)" />
        public void SetCallbacks(IMainActions instance)
        {
            foreach (var item in m_Wrapper.m_MainActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MainActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="MainActions" /> instance referencing this action map.
    /// </summary>
    public MainActions @Main => new MainActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Main" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="MainActions.AddCallbacks(IMainActions)" />
    /// <seealso cref="MainActions.RemoveCallbacks(IMainActions)" />
    public interface IMainActions
    {
        /// <summary>
        /// Method invoked when associated input action "Keyboard X Translate" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnKeyboardXTranslate(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Keyboard Z Translate" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnKeyboardZTranslate(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Keyboard Y Translate" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnKeyboardYTranslate(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Toggle Manipulate Left" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnToggleManipulateLeft(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Toggle Manipulate Right" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnToggleManipulateRight(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Toggle Manipulate Body" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnToggleManipulateBody(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Manipulate Left" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnManipulateLeft(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Manipulate Right" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnManipulateRight(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Manipulate Head" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnManipulateHead(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Hand-Controller Mode" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnHandControllerMode(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Cycle Devices" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCycleDevices(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Stop Manipulation" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnStopManipulation(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Mouse Delta" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMouseDelta(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Mouse Scroll" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMouseScroll(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Rotate Mode Override" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRotateModeOverride(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Toggle Mouse Transformation Mode" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnToggleMouseTransformationMode(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Negate Mode" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnNegateMode(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Z Constraint" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnZConstraint(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "X Constraint" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnXConstraint(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Y Constraint" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnYConstraint(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Reset" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnReset(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Toggle Cursor Lock" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnToggleCursorLock(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Toggle Primary 2D Axis Target" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTogglePrimary2DAxisTarget(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Toggle Secondary 2D Axis Target" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnToggleSecondary2DAxisTarget(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Toggle Device Position Target" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnToggleDevicePositionTarget(InputAction.CallbackContext context);
    }
}
